apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels: 
    app: mysql-app
spec:
  containers:
    - name: mysql
      image: mysql:5-debian
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: mysql123
      ports:
        - containerPort: 3306
