apiVersion: v1
kind: Pod
metadata:
  name: phpmyadmin-pod
  labels:
    app: phpmyadmin
    type: phpmyadmin-app
spec:
  containers: 
    - name: phpmyadmin
      image: phpmyadmin
      ports:
        - containerPort: 80
      env:
        - name: PMA_HOST
          value: mysql-service
        - name: PMA_PORT
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          value: mysql123
